-- tab size is 4
-- registrations for media from the client itself belongs in LibSharedMedia-3.0

if not SharedMedia then return end
local revision = tonumber(string.sub("$Revision: 76383 $", 12, -3))
SharedMedia.revision = (revision > SharedMedia.revision) and revision or SharedMedia.revision

-- -----
-- BACKGROUND
-- -----
SharedMedia:Register("background", "HalBackground1",                    [[Interface\Addons\SharedMedia\background\HalBackground.tga]])
SharedMedia:Register("background", "HalBackground2",                    [[Interface\Addons\SharedMedia\background\HalBackgroundA.tga]])
-- -----
--  BORDER
-- ----
SharedMedia:Register("border", "glowTex1",                             [[Interface\Addons\SharedMedia\border\glowTex1.tga]])
SharedMedia:Register("border", "HalBorder",                             [[Interface\Addons\SharedMedia\border\HalBorder.tga]])
SharedMedia:Register("border", "IshBorder",                             [[Interface\Addons\SharedMedia\border\IshBorder.tga]])
SharedMedia:Register("border", "Rothborder",                            [[Interface\Addons\SharedMedia\border\Rothborder.tga]])
-- -----
--   FONT
-- -----
SharedMedia:Register("font", "Condensed_01",	                        [[Interface\Addons\SharedMedia\fonts\BEBAS.ttf]])
SharedMedia:Register("font", "Condensed_02",			                [[Interface\Addons\SharedMedia\fonts\BigNoodleTitling.ttf]])
SharedMedia:Register("font", "Condensed_03",	                        [[Interface\Addons\SharedMedia\fonts\BigNoodleTitling-Oblique.ttf]])
SharedMedia:Register("font", "Condensed_04",				            [[Interface\Addons\SharedMedia\fonts\Futura LT Condensed Light.ttf]])
SharedMedia:Register("font", "Condensed_05",                            [[Interface\Addons\SharedMedia\fonts\Helvetica LT 67 Medium Condensed.ttf]])
SharedMedia:Register("font", "Condensed_06",					        [[Interface\Addons\SharedMedia\fonts\Tangerine.ttf]])
SharedMedia:Register("font", "Condensed_07",			                [[Interface\Addons\SharedMedia\fonts\ITC Avant Garde Gothic LT Condensed Demi.ttf]])
SharedMedia:Register("font", "Condensed_08",			                [[Interface\Addons\SharedMedia\fonts\ITC Avant Garde Gothic LT Condensed Medium.ttf]])
SharedMedia:Register("font", "Condensed_09",			                [[Interface\Addons\SharedMedia\fonts\ITC Avant Garde Gothic LT Condensed Bold.ttf]])
SharedMedia:Register("font", "Condensed_10",			                [[Interface\Addons\SharedMedia\fonts\ITC Avant Garde Gothic LT Condensed Book.ttf]])
SharedMedia:Register("font", "Condensed_11",				            [[Interface\Addons\SharedMedia\fonts\Trade Gothic LT Bold Condensed No. 20.ttf]])
SharedMedia:Register("font", "Condensed_12",				            [[Interface\Addons\SharedMedia\fonts\LIBEL.ttf]])
SharedMedia:Register("font", "Condensed_13",		                    [[Interface\Addons\SharedMedia\fonts\PLANE___.ttf]])
SharedMedia:Register("font", "Condensed_14",                            [[Interface\Addons\SharedMedia\fonts\ptarm___.ttf]])
SharedMedia:Register("font", "Condensed_15",				            [[Interface\Addons\SharedMedia\fonts\ptarmc__.ttf]])
SharedMedia:Register("font", "Condensed_16",				            [[Interface\Addons\SharedMedia\fonts\ptarmci_.ttf]])
SharedMedia:Register("font", "Condensed_17",				            [[Interface\Addons\SharedMedia\fonts\ptarmi__.ttf]])
SharedMedia:Register("font", "Condensed_18",				            [[Interface\Addons\SharedMedia\fonts\qhyts___.ttf]])
SharedMedia:Register("font", "Condensed_19",				            [[Interface\Addons\SharedMedia\fonts\SF Willamette.ttf]])
SharedMedia:Register("font", "Condensed_20",				            [[Interface\Addons\SharedMedia\fonts\SF Willamette Bold.ttf]])
SharedMedia:Register("font", "Condensed_21",				            [[Interface\Addons\SharedMedia\fonts\SF Willamette Bold Italic.ttf]])
SharedMedia:Register("font", "Condensed_22",				            [[Interface\Addons\SharedMedia\fonts\SF Willamette Italic.ttf]])
SharedMedia:Register("font", "Condensed_23",				            [[Interface\Addons\SharedMedia\fonts\AccidPres.ttf]])
SharedMedia:Register("font", "Condensed_24",				            [[Interface\Addons\SharedMedia\fonts\Cafeta.ttf]])
SharedMedia:Register("font", "Condensed_25",				            [[Interface\Addons\SharedMedia\fonts\HouseGothic LightAltCaps.ttf]])
SharedMedia:Register("font", "Condensed_26",				            [[Interface\Addons\SharedMedia\fonts\HouseGothic LightFour.ttf]])
SharedMedia:Register("font", "Condensed_27",				            [[Interface\Addons\SharedMedia\fonts\HouseGothic LightThree.ttf]])
SharedMedia:Register("font", "Condensed_28",				            [[Interface\Addons\SharedMedia\fonts\Movie Poster Bold.ttf]])
SharedMedia:Register("font", "Condensed_29",				            [[Interface\Addons\SharedMedia\fonts\Prozak Light.ttf]])
SharedMedia:Register("font", "Condensed_30",				            [[Interface\Addons\SharedMedia\fonts\Swiss911ExCompBT.ttf]])
SharedMedia:Register("font", "Condensed_31",				            [[Interface\Addons\SharedMedia\fonts\TRegular.ttf]])
SharedMedia:Register("font", "Condensed_32",				            [[Interface\Addons\SharedMedia\fonts\Vixar.ttf]])
SharedMedia:Register("font", "Pixel_01",					            [[Interface\Addons\SharedMedia\fonts\visitor1.ttf]])
SharedMedia:Register("font", "Pixel_02",					            [[Interface\Addons\SharedMedia\fonts\visitor2.ttf]])
SharedMedia:Register("font", "Pixel_03",	                            [[Interface\Addons\SharedMedia\fonts\SAMSON REGULAR.ttf]])
SharedMedia:Register("font", "Pixel_04",                                [[Interface\Addons\SharedMedia\fonts\SAMSON BOLD.ttf]])
SharedMedia:Register("font", "Pixel_05",	                            [[Interface\Addons\SharedMedia\fonts\SAMSON OBLIQUE.ttf]])
SharedMedia:Register("font", "Pixel_06",	                            [[Interface\Addons\SharedMedia\fonts\SAMSON THIN.ttf]])
SharedMedia:Register("font", "Pixel_07",	                            [[Interface\Addons\SharedMedia\fonts\SAMSON BOLD OBLIQUE.ttf]])
SharedMedia:Register("font", "Pixel_08",	                            [[Interface\Addons\SharedMedia\fonts\SAMSON THIN OBLIQUE.ttf]])
SharedMedia:Register("font", "Pixel_09",				                [[Interface\Addons\SharedMedia\fonts\CharriotDeluxe.ttf]])
SharedMedia:Register("font", "Pixel_10",					            [[Interface\Addons\SharedMedia\fonts\Ernest.ttf]])
SharedMedia:Register("font", "Pixel_11",				                [[Interface\Addons\SharedMedia\fonts\mousetrap.ttf]])
SharedMedia:Register("font", "Pixel_12",	                            [[Interface\Addons\SharedMedia\fonts\FFFMB___.ttf]])
SharedMedia:Register("font", "Pixel_13",				                [[Interface\Addons\SharedMedia\fonts\HISCORE.ttf]])
SharedMedia:Register("font", "Pixel_14",		    	                [[Interface\Addons\SharedMedia\fonts\MicroN55.ttf]])
SharedMedia:Register("font", "Pixel_15",				                [[Interface\Addons\SharedMedia\fonts\MicroN56.ttf]])  
SharedMedia:Register("font", "Pixel_16",					            [[Interface\Addons\SharedMedia\fonts\SKA.ttf]])
SharedMedia:Register("font", "Pixel_17",	                            [[Interface\Addons\SharedMedia\fonts\SF Laundromatic.ttf]])
SharedMedia:Register("font", "Pixel_18",	                            [[Interface\Addons\SharedMedia\fonts\nador.ttf]])
SharedMedia:Register("font", "Pixel_19",				                [[Interface\Addons\SharedMedia\fonts\SilomBol.ttf]])
SharedMedia:Register("font", "Pixel_20",                                [[Interface\Addons\SharedMedia\fonts\04B03.TTF]])
SharedMedia:Register("font", "Pixel_21",                                [[Interface\Addons\SharedMedia\fonts\04B08.TTF]])
SharedMedia:Register("font", "Pixel_22",                                [[Interface\Addons\SharedMedia\fonts\Acme7W.TTF]])
SharedMedia:Register("font", "Pixel_23",                                [[Interface\Addons\SharedMedia\fonts\Acme7WB.TTF]])
SharedMedia:Register("font", "Pixel_24",                                [[Interface\Addons\SharedMedia\fonts\Acme7WBX.TTF]])
SharedMedia:Register("font", "Pixel_25",                                [[Interface\Addons\SharedMedia\fonts\Acme7WX.TTF]])
SharedMedia:Register("font", "Pixel_26",                                [[Interface\Addons\SharedMedia\fonts\Bmf00.ttf]])
SharedMedia:Register("font", "Pixel_27",                                [[Interface\Addons\SharedMedia\fonts\BMSLA.TTF]])
SharedMedia:Register("font", "Pixel_28",                                [[Interface\Addons\SharedMedia\fonts\ELECN.ttf]])
SharedMedia:Register("font", "Pixel_29",                                [[Interface\Addons\SharedMedia\fonts\FleftexM.TTF]])
SharedMedia:Register("font", "Pixel_30",                                [[Interface\Addons\SharedMedia\fonts\FRUCM.TTF]])
SharedMedia:Register("font", "Pixel_31",                                [[Interface\Addons\SharedMedia\fonts\FRUCRG.TTF]])
SharedMedia:Register("font", "Pixel_32",                                [[Interface\Addons\SharedMedia\fonts\FRUCS.TTF]])
SharedMedia:Register("font", "Pixel_33",                                [[Interface\Addons\SharedMedia\fonts\FruityMicrofont.ttf]])
SharedMedia:Register("font", "Pixel_34",                                [[Interface\Addons\SharedMedia\fonts\GRUDBLIT.TTF]])
SharedMedia:Register("font", "Pixel_35",                                [[Interface\Addons\SharedMedia\fonts\Homespun.ttf]])
SharedMedia:Register("font", "Pixel_36",                                [[Interface\Addons\SharedMedia\fonts\HOOG0553.ttf]])
SharedMedia:Register("font", "Pixel_37",                                [[Interface\Addons\SharedMedia\fonts\HOOG0554.ttf]])
SharedMedia:Register("font", "Pixel_38",                                [[Interface\Addons\SharedMedia\fonts\HOOG0555.ttf]])
SharedMedia:Register("font", "Pixel_39",                                [[Interface\Addons\SharedMedia\fonts\HOOG0555cyr2.ttf]])
SharedMedia:Register("font", "Pixel_40",                                [[Interface\Addons\SharedMedia\fonts\HOOG0556.ttf]])
SharedMedia:Register("font", "Pixel_41",                                [[Interface\Addons\SharedMedia\fonts\HOOG0557.ttf]])
SharedMedia:Register("font", "Pixel_42",                                [[Interface\Addons\SharedMedia\fonts\HOOG0558.ttf]])
SharedMedia:Register("font", "Pixel_43",                                [[Interface\Addons\SharedMedia\fonts\HOOG0655.ttf]])
SharedMedia:Register("font", "Pixel_44",                                [[Interface\Addons\SharedMedia\fonts\HOOG0656.ttf]])
SharedMedia:Register("font", "Pixel_45",                                [[Interface\Addons\SharedMedia\fonts\JOEBRG.ttf]])
SharedMedia:Register("font", "Pixel_46",                                [[Interface\Addons\SharedMedia\fonts\Kroe0553.ttf]])
SharedMedia:Register("font", "Pixel_47",                                [[Interface\Addons\SharedMedia\fonts\Kroe0554.ttf]])
SharedMedia:Register("font", "Pixel_48",                                [[Interface\Addons\SharedMedia\fonts\Kroe0555.ttf]])
SharedMedia:Register("font", "Pixel_49",                                [[Interface\Addons\SharedMedia\fonts\Kroe0555caps.ttf]])
SharedMedia:Register("font", "Pixel_50",                                [[Interface\Addons\SharedMedia\fonts\Kroe0556.ttf]])
SharedMedia:Register("font", "Pixel_51",                                [[Interface\Addons\SharedMedia\fonts\Kroe0557.ttf]])
SharedMedia:Register("font", "Pixel_52",                                [[Interface\Addons\SharedMedia\fonts\Kroe0558.ttf]])
SharedMedia:Register("font", "Pixel_53",                                [[Interface\Addons\SharedMedia\fonts\Kyrou9R.ttf]])
SharedMedia:Register("font", "Pixel_54",                                [[Interface\Addons\SharedMedia\fonts\Kyrou9RB.ttf]])
SharedMedia:Register("font", "Pixel_55",                                [[Interface\Addons\SharedMedia\fonts\Kyrou9RBX.ttf]])
SharedMedia:Register("font", "Pixel_56",                                [[Interface\Addons\SharedMedia\fonts\Kyrou9RX.ttf]])
SharedMedia:Register("font", "Pixel_57",                                [[Interface\Addons\SharedMedia\fonts\MARKEN.ttf]])
SharedMedia:Register("font", "Pixel_58",                                [[Interface\Addons\SharedMedia\fonts\minikstt.ttf]])
SharedMedia:Register("font", "Pixel_59",                                [[Interface\Addons\SharedMedia\fonts\nokiafc22.ttf]])
SharedMedia:Register("font", "Pixel_60",                                [[Interface\Addons\SharedMedia\fonts\NOMINAL5.ttf]])
SharedMedia:Register("font", "Pixel_61",                                [[Interface\Addons\SharedMedia\fonts\pf_tempesta_five_bold.ttf]])
SharedMedia:Register("font", "Pixel_62",                                [[Interface\Addons\SharedMedia\fonts\pf_tempesta_five_compressed_bold.ttf]])
SharedMedia:Register("font", "Pixel_63",                                [[Interface\Addons\SharedMedia\fonts\pf_tempesta_five_condensed.ttf]])
SharedMedia:Register("font", "Pixel_64",                                [[Interface\Addons\SharedMedia\fonts\pf_tempesta_five_condensed_bold.ttf]])
SharedMedia:Register("font", "Pixel_65",                                [[Interface\Addons\SharedMedia\fonts\Pixelade.ttf]])
SharedMedia:Register("font", "Pixel_66",                                [[Interface\Addons\SharedMedia\fonts\REDENSEK.ttf]])
SharedMedia:Register("font", "Pixel_67",                                [[Interface\Addons\SharedMedia\fonts\Rprofil6.ttf]])
SharedMedia:Register("font", "Pixel_68",                                [[Interface\Addons\SharedMedia\fonts\SEMPRG.ttf]])
SharedMedia:Register("font", "Pixel_69",                                [[Interface\Addons\SharedMedia\fonts\Squaredance00.ttf]])
SharedMedia:Register("font", "Pixel_70",                                [[Interface\Addons\SharedMedia\fonts\Squaredance10.ttf]])
SharedMedia:Register("font", "Pixel_71",                                [[Interface\Addons\SharedMedia\fonts\STAN0753.TTF]])
SharedMedia:Register("font", "Pixel_72",                                [[Interface\Addons\SharedMedia\fonts\STAN0754.TTF]])
SharedMedia:Register("font", "Pixel_73",                                [[Interface\Addons\SharedMedia\fonts\STAN0755.TTF]])
SharedMedia:Register("font", "Pixel_74",                                [[Interface\Addons\SharedMedia\fonts\STAN0756.TTF]])
SharedMedia:Register("font", "Pixel_75",                                [[Interface\Addons\SharedMedia\fonts\STAN0757caps.TTF]])
SharedMedia:Register("font", "Pixel_76",                                [[Interface\Addons\SharedMedia\fonts\Straightline.ttf]])
SharedMedia:Register("font", "Pixel_77",                                [[Interface\Addons\SharedMedia\fonts\SUPERNAT.TTF]])
SharedMedia:Register("font", "Pixel_78",                                [[Interface\Addons\SharedMedia\fonts\SUPERNAT2.TTF]])
SharedMedia:Register("font", "Pixel_79",                                [[Interface\Addons\SharedMedia\fonts\SUPERNOV.TTF]])
SharedMedia:Register("font", "Pixel_80",                                [[Interface\Addons\SharedMedia\fonts\SWFIT.TTF]])
SharedMedia:Register("font", "Pixel_81",                                [[Interface\Addons\SharedMedia\fonts\TempestaComp.ttf]])
SharedMedia:Register("font", "Pixel_82",                                [[Interface\Addons\SharedMedia\fonts\TempestaCond.ttf]])
SharedMedia:Register("font", "Pixel_83",                                [[Interface\Addons\SharedMedia\fonts\TempestaFive.ttf]])
SharedMedia:Register("font", "Pixel_84",                                [[Interface\Addons\SharedMedia\fonts\TempestaFiveComp.ttf]])
SharedMedia:Register("font", "Pixel_85",                                [[Interface\Addons\SharedMedia\fonts\TempestaFiveCompBold.ttf]])
SharedMedia:Register("font", "Pixel_86",                                [[Interface\Addons\SharedMedia\fonts\TempestaFiveCond.ttf]])
SharedMedia:Register("font", "Pixel_87",                                [[Interface\Addons\SharedMedia\fonts\TempestaFiveCondBold.ttf]])
SharedMedia:Register("font", "Pixel_88",                                [[Interface\Addons\SharedMedia\fonts\V5loxical.ttf]])
SharedMedia:Register("font", "Pixel_89",                                [[Interface\Addons\SharedMedia\fonts\Victor.ttf]])
SharedMedia:Register("font", "Pixel_90",                                [[Interface\Addons\SharedMedia\fonts\Volter.ttf]])
SharedMedia:Register("font", "Pixel_91",	                            [[Interface\Addons\SharedMedia\fonts\SAMSON REGULAR.ttf]])
SharedMedia:Register("font", "Sanserif_01",				                [[Interface\Addons\SharedMedia\fonts\AvantGarde.ttf]])
SharedMedia:Register("font", "Sanserif_02",				                [[Interface\Addons\SharedMedia\fonts\ITC Avant Garde Gothic LT Demi.ttf]])
SharedMedia:Register("font", "Sanserif_03",				                [[Interface\Addons\SharedMedia\fonts\ITC Avant Garde Gothic LT Extra Light.ttf]])
SharedMedia:Register("font", "Sanserif_04",				                [[Interface\Addons\SharedMedia\fonts\ITC Avant Garde Gothic LT Medium.ttf]])
SharedMedia:Register("font", "Sanserif_05",				                [[Interface\Addons\SharedMedia\fonts\ITC Avant Garde Gothic LT Book.ttf]])
SharedMedia:Register("font", "Sanserif_06",				                [[Interface\Addons\SharedMedia\fonts\ITC Avant Garde Gothic LT Bold.ttf]])
SharedMedia:Register("font", "Sanserif_07",				    	        [[Interface\Addons\SharedMedia\fonts\Avanti.ttf]])
SharedMedia:Register("font", "Sanserif_08",				                [[Interface\Addons\SharedMedia\fonts\Avenir LT 55 Roman.ttf]])
SharedMedia:Register("font", "Sanserif_09",				                [[Interface\Addons\SharedMedia\fonts\Avenir LT 85 Heavy.ttf]])
SharedMedia:Register("font", "Sanserif_10",				                [[Interface\Addons\SharedMedia\fonts\Decker.ttf]])
SharedMedia:Register("font", "Sanserif_11",				                [[Interface\Addons\SharedMedia\fonts\DeckerB.ttf]])
SharedMedia:Register("font", "Sanserif_12",				                [[Interface\Addons\SharedMedia\fonts\Futura LT Book.ttf]])
SharedMedia:Register("font", "Sanserif_13",				                [[Interface\Addons\SharedMedia\fonts\Futura LT Heavy.ttf]])
SharedMedia:Register("font", "Sanserif_14",				                [[Interface\Addons\SharedMedia\fonts\Helvetica LT 45 Light.ttf]])
SharedMedia:Register("font", "Sanserif_15",				                [[Interface\Addons\SharedMedia\fonts\Helvetica LT 55 Roman.ttf]])
SharedMedia:Register("font", "Sanserif_16",				                [[Interface\Addons\SharedMedia\fonts\ITC Franklin Gothic LT Book.ttf]])
SharedMedia:Register("font", "Sanserif_17",				                [[Interface\Addons\SharedMedia\fonts\ITC Franklin Gothic LT Demi.ttf]])
SharedMedia:Register("font", "Sanserif_18",	                            [[Interface\Addons\SharedMedia\fonts\Raind___.ttf]])
SharedMedia:Register("font", "Sanserif_19",				                [[Interface\Addons\SharedMedia\fonts\Swiss 721 Light BT.ttf]])
SharedMedia:Register("font", "Sanserif_20",				                [[Interface\Addons\SharedMedia\fonts\Swiss 721 Thin BT.ttf]])
SharedMedia:Register("font", "Sanserif_21",				                [[Interface\Addons\SharedMedia\fonts\Trade Gothic LT.ttf]])
SharedMedia:Register("font", "Sanserif_22",				                [[Interface\Addons\SharedMedia\fonts\Paralucent Light.ttf]])
SharedMedia:Register("font", "Sanserif_23",				                [[Interface\Addons\SharedMedia\fonts\MODENINE.ttf]])
SharedMedia:Register("font", "Sanserif_24",				                [[Interface\Addons\SharedMedia\fonts\SUBAI___.ttf]])
SharedMedia:Register("font", "Sanserif_25",				                [[Interface\Addons\SharedMedia\fonts\SUBARG__.ttf]])
SharedMedia:Register("font", "Sanserif_26",				                [[Interface\Addons\SharedMedia\fonts\weezerfont.ttf]])
SharedMedia:Register("font", "Sanserif_27",				                [[Interface\Addons\SharedMedia\fonts\SOULPAPA.ttf]])
SharedMedia:Register("font", "Sanserif_28",				                [[Interface\Addons\SharedMedia\fonts\SF Willamette Extended.ttf]])
SharedMedia:Register("font", "Sanserif_29",				                [[Interface\Addons\SharedMedia\fonts\AvantGarde Light Medium.ttf]])
SharedMedia:Register("font", "Sanserif_30",				                [[Interface\Addons\SharedMedia\fonts\AvantGarde Light Medium Cond.ttf]])
SharedMedia:Register("font", "Sanserif_31",				                [[Interface\Addons\SharedMedia\fonts\Chalet.ttf]])
SharedMedia:Register("font", "Sanserif_32",				                [[Interface\Addons\SharedMedia\fonts\Conduit.ttf]])
SharedMedia:Register("font", "Sanserif_33",				                [[Interface\Addons\SharedMedia\fonts\Conduit Light.ttf]])
SharedMedia:Register("font", "Sanserif_34",				                [[Interface\Addons\SharedMedia\fonts\Futura Medium.ttf]])
SharedMedia:Register("font", "Sanserif_35",				                [[Interface\Addons\SharedMedia\fonts\LiberationSans Bold.ttf]])
SharedMedia:Register("font", "Sanserif_36",				                [[Interface\Addons\SharedMedia\fonts\LiberationSans Regular.ttf]])
SharedMedia:Register("font", "Sanserif_37",				                [[Interface\Addons\SharedMedia\fonts\MidSerif.ttf]])
SharedMedia:Register("font", "Sanserif_38",				                [[Interface\Addons\SharedMedia\fonts\Myriad Pro.ttf]])
SharedMedia:Register("font", "Sanserif_39",				                [[Interface\Addons\SharedMedia\fonts\Reznor Broken.ttf]])
SharedMedia:Register("font", "Sanserif_40",				                [[Interface\Addons\SharedMedia\fonts\Swiss721MedBT.ttf]])
SharedMedia:Register("font", "Sanserif_41",				                [[Interface\Addons\SharedMedia\fonts\Swiss721nSWA.ttf]])
SharedMedia:Register("font", "Sanserif_42",				                [[Interface\Addons\SharedMedia\fonts\SWISSCB.ttf]])
SharedMedia:Register("font", "Sanserif_43",				                [[Interface\Addons\SharedMedia\fonts\VeraSe.ttf]])
SharedMedia:Register("font", "Serif_01",				                [[Interface\Addons\SharedMedia\fonts\bitstreamvera.ttf]])
-- -----
--   SOUND
-- -----

-- -----
--   STATUSBAR
-- -----
SharedMedia:Register("statusbar", "AANewBar",			                            [[Interface\Addons\SharedMedia\statusbar\AANewBar]])
SharedMedia:Register("statusbar", "Aluminium",			                            [[Interface\Addons\SharedMedia\statusbar\Aluminium]])
SharedMedia:Register("statusbar", "Armory",				                            [[Interface\Addons\SharedMedia\statusbar\Armory]])
SharedMedia:Register("statusbar", "BantoBar",			                            [[Interface\Addons\SharedMedia\statusbar\BantoBar]])
SharedMedia:Register("statusbar", "Cabaret1",			                            [[Interface\Addons\SharedMedia\statusbar\cabaret1]])
SharedMedia:Register("statusbar", "Cabaret2",			                            [[Interface\Addons\SharedMedia\statusbar\cabaret2]])
SharedMedia:Register("statusbar", "Cabaret3",			                            [[Interface\Addons\SharedMedia\statusbar\cabaret3]])
SharedMedia:Register("statusbar", "Cabaret4",			                            [[Interface\Addons\SharedMedia\statusbar\cabaret4]])
SharedMedia:Register("statusbar", "Cabaret5",			                            [[Interface\Addons\SharedMedia\statusbar\cabaret5]])
SharedMedia:Register("statusbar", "Cilo",				                            [[Interface\Addons\SharedMedia\statusbar\Cilo]])
SharedMedia:Register("statusbar", "DarkBottom",			                            [[Interface\Addons\SharedMedia\statusbar\DarkBottom]])
SharedMedia:Register("statusbar", "Delsim01",				                        [[Interface\Addons\SharedMedia\statusbar\DsmB1]])
SharedMedia:Register("statusbar", "Delsim02",				                        [[Interface\Addons\SharedMedia\statusbar\DsmB2]])
SharedMedia:Register("statusbar", "Delsim03",				                        [[Interface\Addons\SharedMedia\statusbar\DsmB3]])
SharedMedia:Register("statusbar", "Delsim04",				                        [[Interface\Addons\SharedMedia\statusbar\DsmB4]])
SharedMedia:Register("statusbar", "Delsim05",				                        [[Interface\Addons\SharedMedia\statusbar\DsmB5]])
SharedMedia:Register("statusbar", "Delsim06",				                        [[Interface\Addons\SharedMedia\statusbar\DsmB6]])
SharedMedia:Register("statusbar", "Delsim07",				                        [[Interface\Addons\SharedMedia\statusbar\DsmB7]])
SharedMedia:Register("statusbar", "Delsim08",				                        [[Interface\Addons\SharedMedia\statusbar\DsmB8]])
SharedMedia:Register("statusbar", "Delsim09",				                        [[Interface\Addons\SharedMedia\statusbar\DsmB9]])
SharedMedia:Register("statusbar", "Delsim10",				                        [[Interface\Addons\SharedMedia\statusbar\DsmV1]])
SharedMedia:Register("statusbar", "Delsim11",				                        [[Interface\Addons\SharedMedia\statusbar\DsmV2]])
SharedMedia:Register("statusbar", "Delsim12",				                        [[Interface\Addons\SharedMedia\statusbar\DsmV3]])
SharedMedia:Register("statusbar", "Delsim13",				                        [[Interface\Addons\SharedMedia\statusbar\DsmV4]])
SharedMedia:Register("statusbar", "Delsim14",				                        [[Interface\Addons\SharedMedia\statusbar\DsmV5]])
SharedMedia:Register("statusbar", "Delsim15",				                        [[Interface\Addons\SharedMedia\statusbar\DsmV6]])
SharedMedia:Register("statusbar", "Delsim16",				                        [[Interface\Addons\SharedMedia\statusbar\DsmV7]])
SharedMedia:Register("statusbar", "Delsim17",				                        [[Interface\Addons\SharedMedia\statusbar\DsmV8]])
SharedMedia:Register("statusbar", "Delsim18",				                        [[Interface\Addons\SharedMedia\statusbar\DsmV9]])
SharedMedia:Register("statusbar", "Delsim19",		                                [[Interface\Addons\SharedMedia\statusbar\DsmOpaqueV1]])
SharedMedia:Register("statusbar", "Delsim20",		                                [[Interface\Addons\SharedMedia\statusbar\DsmOpaqueV2]])
SharedMedia:Register("statusbar", "Delsim21",		                                [[Interface\Addons\SharedMedia\statusbar\DsmOpaqueV3]])
SharedMedia:Register("statusbar", "Delsim22",		                                [[Interface\Addons\SharedMedia\statusbar\DsmOpaqueV4]])
SharedMedia:Register("statusbar", "Delsim23",		                                [[Interface\Addons\SharedMedia\statusbar\DsmOpaqueV5]])
SharedMedia:Register("statusbar", "Delsim24",		                                [[Interface\Addons\SharedMedia\statusbar\DsmOpaqueV6]])
SharedMedia:Register("statusbar", "Delsim25",		                                [[Interface\Addons\SharedMedia\statusbar\DsmOpaqueV7]])
SharedMedia:Register("statusbar", "Delsim26",		                                [[Interface\Addons\SharedMedia\statusbar\DsmOpaqueV8]])
SharedMedia:Register("statusbar", "Duke1",				                            [[Interface\Addons\SharedMedia\statusbar\DukeB]])
SharedMedia:Register("statusbar", "Duke2",				                            [[Interface\Addons\SharedMedia\statusbar\DukeG]])
SharedMedia:Register("statusbar", "Fade1",				                            [[Interface\Addons\SharedMedia\statusbar\fade1]])
SharedMedia:Register("statusbar", "Fade2",				                            [[Interface\Addons\SharedMedia\statusbar\fade2]])
SharedMedia:Register("statusbar", "Flat",				                            [[Interface\Addons\SharedMedia\statusbar\Flat]])
SharedMedia:Register("statusbar", "Glamour",			                            [[Interface\Addons\SharedMedia\statusbar\Glamour2]])
SharedMedia:Register("statusbar", "Glass",				                            [[Interface\Addons\SharedMedia\statusbar\Glass]])
SharedMedia:Register("statusbar", "Glaze",				                            [[Interface\Addons\SharedMedia\statusbar\Glaze]])
SharedMedia:Register("statusbar", "Gloss",				                            [[Interface\Addons\SharedMedia\statusbar\Gloss]])
SharedMedia:Register("statusbar", "Graphite",			                            [[Interface\Addons\SharedMedia\statusbar\Graphite]])
SharedMedia:Register("statusbar", "HalA",				                            [[Interface\Addons\SharedMedia\statusbar\HalA]])
SharedMedia:Register("statusbar", "HalB",				                            [[Interface\Addons\SharedMedia\statusbar\HalB]])
SharedMedia:Register("statusbar", "HalC",				                            [[Interface\Addons\SharedMedia\statusbar\HalC]])
SharedMedia:Register("statusbar", "HalD",				                            [[Interface\Addons\SharedMedia\statusbar\HalD]])
SharedMedia:Register("statusbar", "HalE",				                            [[Interface\Addons\SharedMedia\statusbar\HalE]])
SharedMedia:Register("statusbar", "HalF",				                            [[Interface\Addons\SharedMedia\statusbar\HalF]])
SharedMedia:Register("statusbar", "HalG",				                            [[Interface\Addons\SharedMedia\statusbar\HalG]])
SharedMedia:Register("statusbar", "HalH",				                            [[Interface\Addons\SharedMedia\statusbar\HalH]])
SharedMedia:Register("statusbar", "HalI",				                            [[Interface\Addons\SharedMedia\statusbar\HalI]])
SharedMedia:Register("statusbar", "HalJ",				                            [[Interface\Addons\SharedMedia\statusbar\HalJ]])
SharedMedia:Register("statusbar", "HalK",				                            [[Interface\Addons\SharedMedia\statusbar\HalK]])
SharedMedia:Register("statusbar", "HalL",				                            [[Interface\Addons\SharedMedia\statusbar\HalL]])
SharedMedia:Register("statusbar", "HalM",				                            [[Interface\Addons\SharedMedia\statusbar\HalM]])
SharedMedia:Register("statusbar", "HalN",				                            [[Interface\Addons\SharedMedia\statusbar\HalN]])
SharedMedia:Register("statusbar", "HalO",				                            [[Interface\Addons\SharedMedia\statusbar\HalO]])
SharedMedia:Register("statusbar", "HalP",				                            [[Interface\Addons\SharedMedia\statusbar\HalP]])
SharedMedia:Register("statusbar", "HalQ",				                            [[Interface\Addons\SharedMedia\statusbar\HalQ]])
SharedMedia:Register("statusbar", "HalR",				                            [[Interface\Addons\SharedMedia\statusbar\HalR]])
SharedMedia:Register("statusbar", "HalS",				                            [[Interface\Addons\SharedMedia\statusbar\HalS]])
SharedMedia:Register("statusbar", "HalT",				                            [[Interface\Addons\SharedMedia\statusbar\HalT]])
SharedMedia:Register("statusbar", "HalU",				                            [[Interface\Addons\SharedMedia\statusbar\HalU]])
SharedMedia:Register("statusbar", "HalV",				                            [[Interface\Addons\SharedMedia\statusbar\HalV]])
SharedMedia:Register("statusbar", "HalW",				                            [[Interface\Addons\SharedMedia\statusbar\HalW]])
SharedMedia:Register("statusbar", "HalX",				                            [[Interface\Addons\SharedMedia\statusbar\HalX]])
SharedMedia:Register("statusbar", "Ish00",				                            [[Interface\Addons\SharedMedia\statusbar\Ish00]])
SharedMedia:Register("statusbar", "Ish01",				                            [[Interface\Addons\SharedMedia\statusbar\Ish01]])
SharedMedia:Register("statusbar", "Ish02",				                            [[Interface\Addons\SharedMedia\statusbar\Ish02]])
SharedMedia:Register("statusbar", "Ish03",				                            [[Interface\Addons\SharedMedia\statusbar\Ish03]])
SharedMedia:Register("statusbar", "Ish04",				                            [[Interface\Addons\SharedMedia\statusbar\Ish04]])
SharedMedia:Register("statusbar", "Ish05",				                            [[Interface\Addons\SharedMedia\statusbar\Ish05]])
SharedMedia:Register("statusbar", "Ish06",				                            [[Interface\Addons\SharedMedia\statusbar\Ish06]])
SharedMedia:Register("statusbar", "Ish07",				                            [[Interface\Addons\SharedMedia\statusbar\Ish07]])
SharedMedia:Register("statusbar", "Ish08",				                            [[Interface\Addons\SharedMedia\statusbar\Ish08]])
SharedMedia:Register("statusbar", "Ish09",				                            [[Interface\Addons\SharedMedia\statusbar\Ish09]])
SharedMedia:Register("statusbar", "Ish10",				                            [[Interface\Addons\SharedMedia\statusbar\Ish10]])
SharedMedia:Register("statusbar", "Ish11",				                            [[Interface\Addons\SharedMedia\statusbar\Ish11]])
SharedMedia:Register("statusbar", "Ish12",				                            [[Interface\Addons\SharedMedia\statusbar\Ish12]])
SharedMedia:Register("statusbar", "Ish13",				                            [[Interface\Addons\SharedMedia\statusbar\Ish13]])
SharedMedia:Register("statusbar", "Ish14",				                            [[Interface\Addons\SharedMedia\statusbar\Ish14]])
SharedMedia:Register("statusbar", "Melli",				                            [[Interface\Addons\SharedMedia\statusbar\Melli]])
SharedMedia:Register("statusbar", "Melli Dark",			                            [[Interface\Addons\SharedMedia\statusbar\MelliDark]])
SharedMedia:Register("statusbar", "Minimalist",			                            [[Interface\Addons\SharedMedia\statusbar\Minimalist]])
SharedMedia:Register("statusbar", "Otravi",				                            [[Interface\Addons\SharedMedia\statusbar\Otravi]])
SharedMedia:Register("statusbar", "Savant1",			                            [[Interface\Addons\SharedMedia\statusbar\savant1]])
SharedMedia:Register("statusbar", "Savant2",			                            [[Interface\Addons\SharedMedia\statusbar\savant2]])
SharedMedia:Register("statusbar", "Savant3",			                            [[Interface\Addons\SharedMedia\statusbar\savant3]])
SharedMedia:Register("statusbar", "Savant4",			                            [[Interface\Addons\SharedMedia\statusbar\savant4]])
SharedMedia:Register("statusbar", "Savant5",			                            [[Interface\Addons\SharedMedia\statusbar\savant5]])
SharedMedia:Register("statusbar", "Savant6",			                            [[Interface\Addons\SharedMedia\statusbar\savant6]])
SharedMedia:Register("statusbar", "Savant7",			                            [[Interface\Addons\SharedMedia\statusbar\savant7]])
SharedMedia:Register("statusbar", "Savant8",			                            [[Interface\Addons\SharedMedia\statusbar\savant8]])
SharedMedia:Register("statusbar", "Smooth1",			                            [[Interface\Addons\SharedMedia\statusbar\Smooth]])
SharedMedia:Register("statusbar", "Smooth2",			                            [[Interface\Addons\SharedMedia\statusbar\Smoothv2]])
SharedMedia:Register("statusbar", "Striped",			                            [[Interface\Addons\SharedMedia\statusbar\Striped]])
SharedMedia:Register("statusbar", "Tap1",				                            [[Interface\Addons\SharedMedia\statusbar\tap1]])
SharedMedia:Register("statusbar", "Tap2",				                            [[Interface\Addons\SharedMedia\statusbar\tap2]])
SharedMedia:Register("statusbar", "Tap3",				                            [[Interface\Addons\SharedMedia\statusbar\tap3]])
SharedMedia:Register("statusbar", "Tap4",				                            [[Interface\Addons\SharedMedia\statusbar\tap4]])
SharedMedia:Register("statusbar", "Wglass",				                            [[Interface\Addons\SharedMedia\statusbar\Wglass]])